version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "bigmichi1"
    labels:
      - "dependencies"
      - "automerge"
      - "github_actions"
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
    assignees:
      - "bigmichi1"
    labels:
      - "dependencies"
      - "automerge"
      - "gradle"
