/*
 * This source file was generated by the Gradle 'init' task
 */
package demo;

import java.util.Random;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;

import org.apache.commons.math3.random.RandomGeneratorFactory;

public class Library {

    @Nonnull
    public Double method1() {
        final double random1 = RandomGeneratorFactory.createRandomGenerator(new Random()).nextDouble();
        return random1 * new LibraryOther().method1();
    }

    @Nullable
    public Double method2() {
        return null;
    }
}
