name: Automatic Merge

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'

jobs:
  merge:
    name: Merge Pull Requests
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit

      - uses: nucleos/auto-merge-action@7f954e4bc71c78f231bd0901d0b9b01d3b7b9505 # 1.3.0
        env:
          "GITHUB_TOKEN": ${{ secrets.GRADLE_UPDATE_PAT }}
