name: "Automatic Merge"

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'

jobs:
  merge:
    name: "Merge Pull Requests"
    runs-on: ubuntu-latest

    steps:
      - name: "Merge"
        uses: "nucleos/auto-merge-action@1.2.0"
        env:
          "GITHUB_TOKEN": ${{ secrets.GRADLE_UPDATE_PAT }}
