name: Automatic Merge

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'

jobs:
  merge:
    name: Merge Pull Requests
    runs-on: ubuntu-latest

    steps:
      - uses: nucleos/auto-merge-action@1.3.0
        env:
          "GITHUB_TOKEN": ${{ secrets.GRADLE_UPDATE_PAT }}
